services:
  - type: web
    plan: free
    name: resume-api
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT --workers 2"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
      - key: ENVIRONMENT
        value: production
      - key: ALLOWED_ORIGINS
        value: http://localhost:3000
      - key: REDIS_URL
        value: rediss://default:AWJjAAIjcDE2MzcwOTNkZWVkN2U0NjU1YWNlMzM2ODAyZmFkYWRlMHAxMA@splendid-crappie-25187.upstash.io:6379
      - key: GROQ_API_KEY
        sync: false